### ISSUE TITLE
很好用

### ISSUE THREAD

**Issue by Nergrove** [cactusnix/life-assistant-backend#1]
试了一下，十分好看，也很好用。就是参数能不能支持不需要时间那种？有几个让知道自己几时出生啊，直接支持年月日，按照晚上0点出生就完事儿了。

<sub>Sent from <a href="https://apps.apple.com/cn/app/id1314212521">PPHub</a></sub>

**Comment by cactusnix** [comment]
可以直接填写0点的（eg：1996/8/1 0:0:0），暂时还没有优化默认零点，有时间会优化一下以此来提升体验。😎
